### ISSUE TITLE
Docker images missing "latest" tag

### ISSUE THREAD

**Issue by phlucas96** [apache/incubator-openwhisk-devtools#269] opened 2019-07-04 17:41 UTC
Some of the docker images are missing the "latest" tag, "openwhisk/invoker" and "openwhisk/controller".
As a result, the Makefile used during the Docker compose installation is having errors, such as: "Error response from daemon: manifest for openwhisk/invoker:latest not found".

**Comment by dgrove-oss** [comment] 2019-07-04 22:59
@rabbah @ddragosd -- I don't use docker-compose myself, so I'm not sure what the best semantics are here.  If this is a developer oriented deployment mechanisms, then I suspect it should be doing `openwhisk/FOO_IMAGE:nightly` or `whisk/FOO_IMAGE:latest` depending on whether it is deploying locally built images or pre-built images?  WDYT?

**Comment by tawalaya** [comment] 2019-07-05 09:29
Got the same issue. It looks like the latest tags where deleted on docker-hub which is the cause of the issue. Changing all tags in the compose files and the make file to nightly might work.

**Comment by rabbah** [comment] 2019-07-07 14:42
This PR https://github.com/apache/incubator-openwhisk-devtools/pull/270 should address the issue.

**Comment by dgrove-oss** [comment] 2019-07-09 12:48
merged #270

**Comment by rabbah** [comment] 2019-07-09 18:27
going to speculatively close as fixed y above mentioned PR.

**Closed by rabbah** 2019-07-09 18:27 UTC
